DROP TABLE IF EXISTS APP_USER CASCADE;
DROP TABLE IF EXISTS PLAYER CASCADE;
DROP TABLE IF EXISTS TEAM CASCADE;
DROP TABLE IF EXISTS TOURNAMENT CASCADE;
DROP TABLE IF EXISTS ARENA CASCADE;
DROP TABLE IF EXISTS MATCH_DATA CASCADE;
DROP TABLE IF EXISTS PLAYER_MATCH_STATS CASCADE;
DROP TABLE IF EXISTS PLAYS_FOR CASCADE;
DROP TABLE IF EXISTS PLAYS_AS CASCADE;
DROP TABLE IF EXISTS FAV_PLAYER CASCADE;
DROP TABLE IF EXISTS FAV_TEAM CASCADE;

CREATE TABLE APP_USER
(
user_id INT PRIMARY KEY,
username VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(50) NOT NULL,
is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE PLAYER	
(
player_id INT PRIMARY KEY,
player_name VARCHAR(50) NOT NULL,
platform VARCHAR(50) NOT NULL
);

CREATE table TEAM
(
team_id INT PRIMARY KEY,
team_name VARCHAR(50) NOT NULL UNIQUE,
region VARCHAR(20) NOT NULL
);

CREATE TABLE TOURNAMENT	
(
tournament_id INT PRIMARY KEY,
tournament_name VARCHAR(50) NOT NULL,
country VARCHAR(30) NOT NULL,
start_date DATE NOT NULL,
end_date DATE NOT NULL,
CHECK (end_date >= start_date)
);

CREATE TABLE ARENA
(
arena_id INT PRIMARY KEY,
arena_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MATCH_DATA (
match_id SERIAL PRIMARY KEY,
match_date DATE NOT NULL,
tournament_stage VARCHAR(30) NOT NULL,
weather VARCHAR(20) NOT NULL,
tournament_id INT,
arena_id INT NOT NULL
);

CREATE TABLE PLAYER_MATCH_STATS	
(
player_id INT NOT NULL,
match_id INT NOT NULL,
goals INT NOT NULL CHECK (goals >= 0),
assists INT NOT NULL CHECK (assists >= 0),
saves INT NOT NULL CHECK (saves >= 0),
shot_accuracy DECIMAL(5,2) NOT NULL CHECK (shot_accuracy >= 0 AND shot_accuracy <= 100),
mvp BOOLEAN NOT NULL DEFAULT FALSE,
PRIMARY KEY(player_id, match_id),
FOREIGN KEY (player_id) REFERENCES PLAYER(player_id),
FOREIGN KEY (match_id) REFERENCES MATCH_DATA(match_id)
);

CREATE TABLE PLAYS_FOR
(
player_id INT NOT NULL,
team_id INT NOT NULL,
since DATE NOT NULL,
until DATE,
CHECK (until IS NULL OR until >= since),
PRIMARY KEY (player_id, team_id, since),
FOREIGN KEY (player_id) REFERENCES PLAYER(player_id),
FOREIGN KEY (team_id) REFERENCES TEAM(team_id)
);

CREATE TABLE PLAYS_AS	
(
team_id INT NOT NULL,
match_id INT NOT NULL,
team_type VARCHAR(6) NOT NULL CHECK (team_type IN ('ORANGE', 'BLUE')),
PRIMARY KEY(team_id, match_id),
FOREIGN KEY (team_id) REFERENCES TEAM(team_id),
FOREIGN KEY (match_id) REFERENCES MATCH_DATA(match_id)
);

CREATE TABLE FAV_PLAYER
(
user_id INT NOT NULL, 
player_id  INT NOT NULL,
PRIMARY KEY(user_id, player_id),
FOREIGN KEY (user_id) REFERENCES APP_USER(user_id),
FOREIGN KEY (player_id) REFERENCES PLAYER(player_id)
);

CREATE TABLE FAV_TEAM	
(
user_id INT NOT NULL,
team_id  INT NOT NULL,
PRIMARY KEY(user_id, team_id),
FOREIGN KEY (user_id) REFERENCES APP_USER(user_id),
FOREIGN KEY (team_id) REFERENCES TEAM(team_id)
);
